name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Add dependency '...'
        2. Call function '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) are affected?
      multiple: true
      options:
        - Android
        - iOS
        - JVM
        - Linux
        - macOS
        - Windows
        - All platforms
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Library version
      description: What version of the library are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: kotlin-version
    attributes:
      label: Kotlin version
      description: What version of Kotlin are you using?
      placeholder: "2.1.0"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here (logs, screenshots, etc.)

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing issues that describe my problem
          required: true
        - label: I have read the documentation
          required: true
